### PR TITLE
fix: adapt for latest @octokit/types

### LINKED ISSUE #65: broken types in newer version of octokit types
I was hoping to use this plugin, sadly it fails on compile.

Seems `PullsCreateResponseData` is no more and `TreeParameter` is [outdated](https://github.com/octokit/types.ts/blob/241cc2c5f09a533fa3fd3bc2764294ce1f584956/src/generated/Endpoints.ts#L4162-L4165)

```
node_modules/octokit-plugin-create-pull-request/dist-types/compose-create-pull-request.d.ts:3:243 - error TS2694: Namespace '"C:/git/code/ghaction.file.sync/node_modules/@octokit/types/dist-types/index"' has no exported member 'PullsCreateResponseData'.

3 export declare function composeCreatePullRequest(octokit: Octokit, { owner, repo, title, body, base, head, createWhenEmpty, changes: changesOption, draft, }: Options): Promise<import("@octokit/types").OctokitResponse<import("@octokit/types").PullsCreateResponseData> | null>;

                                                            ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/octokit-plugin-create-pull-request/dist-types/index.d.ts:7:122 - error TS2694: Namespace '"C:/git/code/ghaction.file.sync/node_modules/@octokit/types/dist-types/index"' has no exported member 'PullsCreateResponseData'.

7     createPullRequest: (__1: Types.Options) => Promise<import("@octokit/types").OctokitResponse<import("@octokit/types").PullsCreateResponseData> | null>;
                                                                                                                           ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/octokit-plugin-create-pull-request/dist-types/types.d.ts:3:47 - error TS2339: Property 'POST /repos/:owner/:repo/git/trees' does not exist on type 'Endpoints'.

3 export declare type TreeParameter = Endpoints["POST /repos/:owner/:repo/git/trees"]["parameters"]["tree"];
```

### PR DESCRIPTION
**Pull request by jetersen**
Package-lock had locked `@octokit/types` to version `5.x.x`...

fixes #65

### CODE REVIEW

File: src/compose-create-pull-request.ts [hunk 1]
```diff
@@ -57,17 +57,17 @@ export async function composeCreatePullRequest(
...
 
     // https://developer.github.com/v3/repos/forks/#list-forks
-    const forks = await octokit.request("GET /repos/:owner/:repo/forks", {
+    const forks = await octokit.request("GET /repos/{owner}/{repo}/forks", {
       owner,
       repo,
     });
     const hasFork = forks.data.find(
-      (fork) => fork.owner.login === user.data.login
+      (fork) => fork!.owner!.login === user.data.login
```
Comment (jetersen) [inline src/compose-create-pull-request.ts:65]: Not sure what the right approach here is since if you use `fork?.owner?.login` code coverage decreases.

File: src/compose-create-pull-request.ts [hunk 2]
```diff
@@ -79,13 +79,13 @@ export async function composeCreatePullRequest(
...
     data: [latestCommit],
-  } = await octokit.request("GET /repos/:owner/:repo/commits", {
+  } = await octokit.request("GET /repos/{owner}/{repo}/commits", {
     owner,
     repo,
     sha: base,
     per_page: 1,
   });
-  state.latestCommitSha = latestCommit.sha;
+  state.latestCommitSha = latestCommit.sha as string;
```
Comment (gr2m) [inline src/compose-create-pull-request.ts:88]: Can you update `package-lock.json` so that `@octokit/types` 6.3.0+ is used? Then you can remove the ` as string`

```suggestion
  state.latestCommitSha = latestCommit.sha;
```

**Review by gr2m — CHANGES_REQUESTED** [review]
This is great! I left two suggestions to bring bring it over the finish line :)

File: src/types.ts [hunk 3]
```diff
@@ -1,7 +1,7 @@
 import type { Octokit } from "@octokit/core";
 import type { Endpoints } from "@octokit/types";
 
-export type TreeParameter = Endpoints["POST /repos/:owner/:repo/git/trees"]["parameters"]["tree"];
+export type TreeParameter = Endpoints["POST /repos/{owner}/{repo}/git/trees"]["parameters"]["tree"];
```
Comment (gr2m) [inline src/types.ts:4]: I think we should add `@octokit/types` as a direct dependency of this package, as we use it in the code, that will make it more predictable. And I've seen `yarn` users having problems when using sub-dependencies

Comment (jetersen) [reply src/types.ts:4]: will do!

**Review by gr2m — APPROVED** [review]
Mange tak!

**Comment by jetersen** [comment]
Selv tak!
